// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATH7wVqDs1FSkqO92JYnsYwWRrX5_TFgY',
    appId: '1:528396478451:android:6b6add9d6f501ff727d486',
    messagingSenderId: '528396478451',
    projectId: 'companion-app-test-a5c5f',
    storageBucket: 'companion-app-test-a5c5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_f_LanEM7t5AOcu4zoEY5M2nWdnp8W6k',
    appId: '1:528396478451:ios:814d36a57a5af35327d486',
    messagingSenderId: '528396478451',
    projectId: 'companion-app-test-a5c5f',
    storageBucket: 'companion-app-test-a5c5f.appspot.com',
    iosClientId:
        '528396478451-fn3gqg495of382sf9qp4bkdlvbt5kvbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.companionApp',
  );
}
